---
- name: Job Template Creation
  hosts: localhost
  tasks:
    - name: Create a job_template with a specific instance group
      ansible.controller.job_template:
        name: "New Job Template using instance group {{igroup_name}}"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "ansible-tower-examples"
        playbook: "ping.yml"
        instance_groups: ["{{igroup_name}}"]
        state: "present"
    - name: Add user ibm to the newly created job template
      ansible.controller.role:
        user: "ibm"
        role: admin
        job_templates:
          -  "New Job Template using instance group {{igroup_name}}"
        state: present
