---
- name: network stats command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: show interface stats command
      cli_command:
        command: "show interface GigabitEthernet1"
      when: ansible_network_os is defined
      register: output

    - name: Update incident
      servicenow.itsm.incident:
        number: "{{ SNOW_INC_NUMBER }}"
        instance:
          host: "{{ SNOW_HOST }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
          timeout: "{{ SNOW_TIMEOUT }}"
        state: in_progress
        other:
          comments: "Ansible Automation Platform output of 'show interface GigabitEthernet1' command:\n{{ output.stdout }}"

